package dmc.brewjournal.vaadin;

import java.util.Collections;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

import dmc.brewjournal.entity.Batch;

public class BatchListView extends CustomComponent {

	private static final long serialVersionUID = -2636568370976334462L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table tblBatchList;
	@AutoGenerated
	private Button btnNewBatch;
	@AutoGenerated
	private Label lblMyBrewJournal;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private Batch selectedBatch = null;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BatchListView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		addEventListenters();
	}

	/**
	 * Add event listeners, such as button click handlers.
	 */
	protected void addEventListenters() {
		
		// handle New Batch button click
		btnNewBatch.addListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1390375932758670734L;
			@Override
			public void buttonClick(ClickEvent event) {
				// replace Application->MainWindow with BatchDetailView
				AppMain app = (AppMain) getApplication();
				app.showDetailView();
//				app.getMainWindow().removeComponent(AppData.getBatchListView());
//				app.getMainWindow().addComponent(AppData.getBatchDetailView());
			}
		});
		
		tblBatchList.setSelectable(true);
		tblBatchList.addListener(new Property.ValueChangeListener() {			
			@Override
			public void valueChange(ValueChangeEvent event) {
				Batch batch = (Batch)((Table) event.getProperty()).getValue();
				setSelectedBatch(batch);
			}
		});
	}
	
	/**
	 * Refresh the list of batches
	 * @return
	 */
	protected void refreshBatchListTable() {
		List<Batch> batchList = AppData.getBrewJournalService().findAll();
		
		Collections.sort(batchList);
		
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// lblMyBrewJournal
		lblMyBrewJournal = new Label();
		lblMyBrewJournal.setImmediate(false);
		lblMyBrewJournal.setWidth("-1px");
		lblMyBrewJournal.setHeight("-1px");
		lblMyBrewJournal.setValue("My Brew Journal");
		mainLayout.addComponent(lblMyBrewJournal);
		mainLayout.setComponentAlignment(lblMyBrewJournal, new Alignment(20));
		
		// btnNewBatch
		btnNewBatch = new Button();
		btnNewBatch.setCaption("New Batch");
		btnNewBatch.setImmediate(true);
		btnNewBatch.setWidth("-1px");
		btnNewBatch.setHeight("-1px");
		mainLayout.addComponent(btnNewBatch);
		
		// tblBatchList
		tblBatchList = new Table();
		tblBatchList.setImmediate(false);
		tblBatchList.setWidth("100.0%");
		tblBatchList.setHeight("-1px");
		mainLayout.addComponent(tblBatchList);
		
		return mainLayout;
	}

	public Batch getSelectedBatch() {
		return selectedBatch;
	}

	public void setSelectedBatch(Batch selectedBatch) {
		this.selectedBatch = selectedBatch;
	}

}
